#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="ninja-build"
DESC="Small build system with a focus on speed"
VERSION="1.11.1"
WEBSITE="https://$NAME.org/"
LICENSE="Apache-2.0"

RUNTIME_DEPS=""
COMPILE_DEPS="re2c"
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD="https://github.com/$NAME/ninja/archive/refs/tags/v$VERSION.tar.gz"
KEEP_FILES=""

conf() {
	python3 configure.py
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	ninja -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	ad -p "$INSTALLTO/bin/"
	c ninja "$INSTALLTO/bin/ninja"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation."
		exit 1
		;;
esac
