#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="tcl"
DESC="The tool command language"
VERSION="8.6.14"
WEBSITE="https://$NAME.sourceforge.net"
LICENSE="TCL"

RUNTIME_DEPS=""
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD="http://prdownloads.sourceforge.net/$NAME/$NAME$VERSION-src.tar.gz"
KEEP_FILES=""

conf() {
	cd unix
	./configure --prefix="/usr"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	cd unix
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	cd unix
	make DESTDIR="$INSTALLTO" install
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
