#!/bin/bash
export A="$1"
source "./metadata.mixdata"

get() {
	wget -c "https://ftp.gnu.org/gnu/$NAME/$NAME-$VERSION.tar.xz" "$NAME-$VERSION.tar.xz"
}

unpack() {
	# Here we will unpack tarball with source
	ad unpacked
	tar -xvf ./*tar* -C unpacked
	exit "$?"
	echo "Contents of 'unpacked'"
	l unpacked
}
conf() {
	# This is were package source should be configured
	cd unpacked
	cd *
	mkdir build
	cd build
	../configure --prefix="/usr"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	# This function build a package
	cd unpacked
	cd *
	cd build
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	# Here we're going to install a package to local database and set up some things (if needed)
	cd unpacked
	cd *
	cd build
	make DESTDIR="$INSTALLTO" install
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"get")
		get;;
	"unpack")
		unpack;;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
