#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="lzop"
DESC="One of the fastest compressor and decompressor around"
VERSION="1.04"
WEBSITE="https://www.lzop.org"
LICENSE="GPL-2"

RUNTIME_DEPS=""
COMPILE_DEPS=""
BOTH_DEPS=("lzo")
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

DOWNLOAD="$WEBSITE/download/$NAME-$VERSION.tar.gz" "$NAME-$VERSION.tar.gz"

REPLACES=""
CONFLICTS=""

KEEP_FILES=""

ERR() {
	if [[ $1 != 0 ]]
	then
		echo "- Previous command returned with exit code: $1"
		exit $1
	fi
}

conf() {
	./configure --prefix="/usr"
	ERR $?
}
comp() {
	make -j"$PROC"
	ERR $?
}
setup() {
	make DESTDIR="$INSTALLTO" install 
	ERR $?
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
