#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="pkgset-boot"
DESC="Virtual package, that adds basic booting support"
VERSION="0.1"
WEBSITE="https://carrot.leniwiak.pl"
LICENSE="GPL-2"

RUNTIME_DEPS=("grub" "efivar" "efibootmgr" "linux")
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD=""
KEEP_FILES=""

conf() {
	exit 0
}
comp() {
	exit 0
}
setup() {
	exit 0
}

case "$A" in
	"none")
		echo -ne "";;
	"unpack")
		unpack;;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
