#!/bin/bash
export A="$1"

# More help:
# https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html#Simple-configuration

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="grub"
DESC="A program that allows you to boot your system with BIOS"
VERSION="2.12"
WEBSITE="https://www.gnu.org/software/grub/index.html"
LICENSE="GPL-2"

RUNTIME_DEPS=("lvm2" "efibootmgr")
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD="http://ftp.gnu.org/gnu/$NAME/$NAME-$VERSION.tar.xz"

KEEP_FILES="/etc/default/grub"

ERR() {
	if [[ $1 != 0 ]]
	then
		echo "- Previous command returned with exit code: $1"
		exit $1
	fi
}

conf() {
	./configure --prefix="/usr" --bindir="/usr/bin" --sbindir="/usr/sbin" --mandir="/usr/share/man" --infodir="/usr/share/info" --datarootdir="/usr/share" --sysconfdir="/etc" --with-bootdir="/boot" --with-grubdir="grub"  --with-platform=efi --target=x86_64 --enable-nls --enable-device-mapper
	ERR $?
}
comp() {
	echo "depends bli part_gpt" > grub-core/extra_deps.lst
	ERR $?
	make -j"$PROC"
	ERR $?
}
setup() {
	make DESTDIR="$INSTALLTO" install
	ERR $?
	ad -p "$INSTALLTO"/etc/default
	ERR $?
	c -o ../../config "$INSTALLTO"/etc/default/grub
	ERR $?
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
