#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="libuuid"
DESC="Disk UUID generation library"
VERSION="2.40.2"
WEBSITE="https://github.com/util-linux/util-linux"
LICENSE="GPL-2"

RUNTIME_DEPS=""
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""
DOWNLOAD="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-$VERSION.tar.xz"
KEEP_FILES=""

conf() {
	./configure --prefix="/usr" --disable-all-programs --enable-libuuid
	exit 0
}
comp() {
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	make DESTDIR="$INSTALLTO" install-strip
	cd "$INSTALLTO"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
