#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="basefs"
DESC="Basic set of files and directrories needed by CarrotOS"
VERSION="0.1"
WEBSITE="https://carrot.leniwiak.pl"
LICENSE="GPL-2"

RUNTIME_DEPS=""
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD=""

KEEP_FILES=""

conf() {
	echo "carrot-$RANDOM" > etc/hostname
	exit 0
}
comp() {
	exit 0
}
setup() {
	cd ..
	m unpacked "$INSTALLTO"
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
