#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER="oliwiernowicki4@gmail.com"

NAME="libx11"
DESC="Library routines that are used within all X Window applications"
VERSION="1.8.9"
WEBSITE="https://www.x.org/wiki/"
LICENSE="BSD"

RUNTIME_DEPS=""
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD="https://www.x.org/archive//individual/lib/$NAME-$VERSION.tar.gz"

KEEP_FILES=""

conf() {
	./configure --prefix="/usr"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	make DESTDIR="$INSTALLTO" install
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
