#!/bin/bash
export A="$1"
source "./metadata.mixdata"

DOWNLOAD="http://static.rust-lang.org/dist/rustc-$VERSION-src.tar.gz"
conf() {
	# This is were package source should be configured
	cd unpacked
	cd *
	c ../../Config.toml config.toml
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	# This function build a package
	cd unpacked
	cd *
	python3 x.py build
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	# Here we're going to install a package to local database and set up some things (if needed)
	cd unpacked
	cd *
	DESTDIR="$INSTALLTO" python3 x.py install
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd "$INSTALLTO"/usr/lib/
	ad "x86_64-unknown-linux-gnu"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	m "rustlib/x86_64-unknown-linux-gnu/lib/" "x86_64-unknown-linux-gnu/"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	rd "rustlib" -r
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
