#!/bin/bash
export A="$1"
source "./metadata.mixdata"

DOWNLOAD="https://github.com/mesonbuild/$NAME/archive/refs/tags/$VERSION.tar.gz"

conf() {
	# This is were package source should be configured
	exit 0
}
comp() {
	# This function builds a package
	exit 0
}
setup() {
	# Here we're going to install a package to local database and set up some things (if needed)
	cd unpacked
	cd *
	ad -p "$INSTALLTO/bin/"
	c meson.py "$INSTALLTO/bin/meson"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation."
		exit 1
		;;
esac
