#!/bin/bash
export A="$1"
source "./metadata.mixdata"

DOWNLOAD="http://cdn.kernel.org/pub/linux/kernel/v6.x/$NAME-$VERSION.tar.xz"

conf() {
	exit 0
}
comp() {
	# This function build a package
	exit 0
}
setup() {
	source metadata.mixdata
	# Here we're going to install a package to local database and set up some things (if needed)
	cd unpacked
	cd *
	rd -r ./usr/
	make headers_install
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	ad "$INSTALLTO/usr/include/" || exit 1
	c -o "usr/include/" "$INSTALLTO/usr/include/" || exit 1
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
