#!/bin/bash
export A="$1"
source "./metadata.mixdata"

DOWNLOAD="http://www.cpan.org/src/5.0/$NAME-$VERSION.tar.gz"
conf() {
	# This is were package source should be configured
	cd unpacked
	cd *
	./Configure -des -Dprefix=/usr
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	# This function build a package
	cd unpacked
	cd *
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	# Here we're going to install a package to local database and set up some things (if needed)
	cd unpacked
	cd *
	make DESTDIR="$INSTALLTO" install
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd "$INSTALLTO/usr/lib/perl5/"
	sl "$VERSION" "5.38"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
