#!/bin/bash
export A="$1"
source "./metadata.mixdata"

get() {
	wget -c "https://cdn.kernel.org/pub/linux/kernel/v6.x/$NAME-$VERSION.tar.xz" "$NAME-$VERSION.tar.xz"
}

unpack() {
	# Here we will unpack tarball with source
	ad unpacked
	tar -xvf ./*tar* -C unpacked
	exit "$?"
	echo "Contents of 'unpacked'"
	l unpacked
}
conf() {
	# This is were package source should be configured
	cd unpacked
	cd *
	make defconfig
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
comp() {
	# This function build a package
	cd unpacked
	cd *
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	source metadata.mixdata
	# Here we're going to install a package to local database and set up some things (if needed)
	cd unpacked
	cd *
	ad "$INSTALLTO/boot/" || exit 1
	c arch/x86/boot/bzImage "$INSTALLTO/boot/bzImage-$VERSION" || exit 1
	c System.map "$INSTALLTO/boot/System.map-$VERSION" || exit 1
	c .config "$INSTALLTO/boot/config-$VERSION" || exit 1
	cd "$INSTALLTO/boot" || exit 1
	sl "bzImage-$VERSION" "bzImage" || exit 1
	sl "System.map-$VERSION" "System.map" || exit 1
	sl "config-$VERSION" "config" || exit 1
	cd ..
}

case "$A" in
	"get")
		get;;
	"unpack")
		unpack;;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
