#!/bin/bash
export A="$1"

MAINTAINER="Leniwiak"
MAINTAINER_CONTACT="oliwiernowicki4@gmail.com"

NAME="zlib"
VERSION="1.3"
WEBSITE="https://www.$NAME.net"
LICENSE="GPL-2"
DESC="A massively spiffy yet delicately unobtrusive compression library"

RUNTIME_DEPS=""
COMPILE_DEPS=""
BOTH_DEPS=""
EXTRA_RUNTIME_DEPS=""
EXTRA_COMPILE_DEPS=""
EXTRA_BOTH_DEPS=""

REPLACES=""
CONFLICTS=""

DOWNLOAD="http://www.$NAME.net/$NAME-$VERSION.tar.xz"
KEEP_FILES=""

conf() {
	./configure --prefix="/usr"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
}
comp() {
	make -j"$PROC"
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
	exit "$?"
}
setup() {
	make DESTDIR="$INSTALLTO" install 
	exitcode="$?"
	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
	cd ..
}

case "$A" in
	"none")
		echo -ne "";;
	"conf")
		conf;;
	"comp")
		comp;;
	"setup")
		setup;;
	*)
		echo "Unknown operation. Fail."
		exit 1
		;;
esac
